extends SceneTree
const Dock := preload("res://addons/GDDraw/gddraw_dock.gd")
const Canvas := preload("res://addons/GDDraw/gddraw_canvas.gd")
var assertions := 0
var failures := 0
func _initialize(): _run.call_deferred()
func check(ok: bool, message: String):
	assertions += 1
	if not ok:
		failures += 1
		push_error(message)
func settle():
	for i in range(6): await process_frame
func point(canvas: Control, pixel: Vector2i) -> Vector2:
	return canvas._image_pixels_to_local_rect(Rect2i(pixel, Vector2i.ONE)).get_center()
func choose(dock: Control, id: String, tool: int):
	var target = dock._layer_session.get_active_target()
	target.select_layer(id)
	dock._sync_canvas_to_active_layer()
	dock._select_tool(tool)
func click_tree(dock: Control, id: String, shift := false, ctrl := false, right := false):
	var target = dock._layer_session.get_active_target()
	var item: TreeItem = dock._find_layers_tree_item(dock._layers_tree.get_root(), "paint", target.target_id, id, "")
	var event := InputEventMouseButton.new()
	event.button_index = MOUSE_BUTTON_RIGHT if right else MOUSE_BUTTON_LEFT
	event.shift_pressed = shift
	event.ctrl_pressed = ctrl
	event.position = dock._layers_tree.global_position + dock._layers_tree.get_item_area_rect(item, 0).get_center()
	event.global_position = event.position
	event.pressed = true
	root.push_input(event)
	event = event.duplicate()
	event.pressed = false
	root.push_input(event)
	await settle()
func _run():
	if "--rename-only" in OS.get_cmdline_user_args():
		root.size = Vector2i(1200, 800)
		await rename_reclick_checks()
		print("Layer rename: %d assertions, %d failures" % [assertions, failures])
		quit(1 if failures else 0)
		return
	var dock := Dock.new()
	root.add_child(dock)
	dock.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	await settle()
	dock._layer_session.initialize_2d(Vector2i(64,64))
	dock._sync_canvas_to_active_layer()
	dock._select_tool(Canvas.ToolMode.GRADIENT)
	var canvas = dock._canvas
	canvas.begin_gradient(Vector2.ZERO)
	canvas.update_gradient(Vector2(63,0))
	canvas.commit_gradient()
	var target = dock._layer_session.get_active_target()
	var gradient_id: String = target.selected_layer_id
	dock._select_tool(Canvas.ToolMode.TEXT)
	canvas.create_text_draft(Rect2i(2,2,60,40), "Text")
	canvas.commit_text_draft()
	var text_id: String = target.selected_layer_id
	check(target.find_node(text_id).is_text_layer() and text_id != gradient_id, "Text tool creates Text above Gradient")
	for id in [gradient_id, text_id]:
		choose(dock, id, Canvas.ToolMode.BRUSH)
		target = dock._layer_session.get_active_target()
		var original: PackedByteArray = target.find_node(id).image.get_data()
		var count: int = target.get_paint_layer_count()
		check(target.get_paint_layer_count() == count and target.selected_layer_id == id, "tool selection alone creates nothing")
		canvas.brush_color = Color.RED
		canvas._begin_stroke(point(canvas, Vector2i(20,20)))
		canvas._end_stroke()
		await settle()
		check(target.get_paint_layer_count() == count + 1 and not target.get_selected_layer().is_editable_layer(), "brush creates a paint sibling")
		check(target.find_node(id).image.get_data() == original, "brush preserves editable source pixels")
		dock._undo()
		target = dock._layer_session.get_active_target()
		check(target.get_paint_layer_count() == count and target.selected_layer_id == id, "one undo removes stroke and automatic layer")
		dock._redo()
		target = dock._layer_session.get_active_target()
		check(target.get_paint_layer_count() == count + 1 and not target.get_selected_layer().image.is_invisible(), "redo restores automatic layer and pixels")
		choose(dock, id, Canvas.ToolMode.BRUSH)
		count = target.get_paint_layer_count()
		canvas.brush_color = Color.TRANSPARENT
		canvas._begin_stroke(point(canvas, Vector2i(20,20)))
		canvas._end_stroke()
		await settle()
		target = dock._layer_session.get_active_target()
		check(target.get_paint_layer_count() == count and target.selected_layer_id == id, "transparent stroke leaves no empty layer")
		canvas.brush_color = Color.BLUE
		canvas._begin_stroke(point(canvas, Vector2i(20,20)))
		canvas._cancel_stroke()
		await settle()
		target = dock._layer_session.get_active_target()
		check(target.get_paint_layer_count() == count and target.selected_layer_id == id, "canceled brush leaves no layer")
		choose(dock, id, Canvas.ToolMode.RECTANGLE)
		canvas._begin_shape_preview(point(canvas, Vector2i(4,4)))
		canvas.cancel_active_selection_or_preview()
		await settle()
		target = dock._layer_session.get_active_target()
		check(target.get_paint_layer_count() == count, "canceled shape leaves no layer")
		choose(dock, id, Canvas.ToolMode.FILL)
		canvas._fill_at_position(point(canvas, Vector2i(4,4)))
		check(target.get_paint_layer_count() == count + 1, "fill creates a paint layer")
		dock._undo()
		target = dock._layer_session.get_active_target()
		choose(dock, id, Canvas.ToolMode.ERASER)
		canvas._begin_stroke(point(canvas, Vector2i(4,4)))
		check(target.get_paint_layer_count() == count and target.selected_layer_id == id, "eraser neither rasterizes nor adds empty layer")
		target.set_node_locked(id, true)
		choose(dock, id, Canvas.ToolMode.BRUSH)
		canvas._begin_stroke(point(canvas, Vector2i(4,4)))
		check(target.get_paint_layer_count() == count, "locked editable layer cannot auto-create paint")
		target.set_node_locked(id, false)
	choose(dock, gradient_id, Canvas.ToolMode.TEXT)
	dock._on_text_default_output_selected(1)
	var before_count: int = target.get_paint_layer_count()
	canvas.create_text_draft(Rect2i(1,1,60,40), "Raster")
	canvas.cancel_text_draft()
	await settle()
	target = dock._layer_session.get_active_target()
	check(target.get_paint_layer_count() == before_count, "canceled raster Text removes automatic paint layer")
	canvas.create_text_draft(Rect2i(1,1,60,40), "Raster")
	canvas.commit_text_draft()
	check(target.get_paint_layer_count() == before_count + 1 and not target.get_selected_layer().is_editable_layer(), "Text raster preference uses new paint layer")
	choose(dock, text_id, Canvas.ToolMode.GRADIENT)
	dock._on_gradient_default_output_selected(1)
	before_count = target.get_paint_layer_count()
	canvas.begin_gradient(Vector2(5,5))
	canvas.commit_gradient()
	await settle()
	target = dock._layer_session.get_active_target()
	check(target.get_paint_layer_count() == before_count, "zero-length raster Gradient leaves no layer")
	canvas.begin_gradient(Vector2(5,5))
	canvas.update_gradient(Vector2(60,5))
	canvas.commit_gradient()
	check(target.get_paint_layer_count() == before_count + 1 and not target.get_selected_layer().is_editable_layer(), "Gradient raster preference uses new paint layer")
	await selection_checks(dock)
	await bulk_checks(dock)
	await panel_preference_checks(dock)
	await gradient_context_checks(dock)
	dock.queue_free()
	await settle()
	await rename_reclick_checks()
	print("Layer workflows: %d assertions, %d failures" % [assertions, failures])
	quit(1 if failures else 0)

func rename_reclick_checks():
	var dock := Dock.new()
	root.add_child(dock)
	dock.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	await settle()
	dock._layer_session.initialize_2d(Vector2i(32, 32))
	var target = dock._layer_session.get_active_target()
	var first: String = target.selected_layer_id
	target.add_paint_layer("Other")
	dock._sync_canvas_to_active_layer()
	dock._refresh_layers_tree()
	dock._panel_host.activate_panel("layers")
	await settle()
	var tree = dock._layers_tree
	var item: TreeItem = dock._find_layers_tree_item(tree.get_root(), "paint", target.target_id, first)
	tree.deselect_all()
	item.select(0)
	dock._on_layers_tree_multi_selected(item, 0, true)
	await settle()
	check(tree.stable_selected_context.get("node_id") == first, "multi-selection updates second-click identity when selecting another layer")
	item = dock._find_layers_tree_item(tree.get_root(), "paint", target.target_id, first)
	check(not item.is_editable(0), "first selection does not start rename")
	var event := InputEventMouseButton.new()
	event.button_index = MOUSE_BUTTON_LEFT
	event.position = tree.get_item_area_rect(item, 0).get_center()
	event.pressed = true
	tree._gui_input(event)
	event.pressed = false
	tree._gui_input(event)
	await settle()
	item = dock._find_layers_tree_item(tree.get_root(), "paint", target.target_id, first)
	check(item.is_editable(0) and dock._layers_rename_context.get("node_id") == first, "second click starts native inline rename after selecting another layer")
	dock._cancel_layer_inline_rename()
	await settle()
	item = dock._find_layers_tree_item(tree.get_root(), "paint", target.target_id, first)
	event.position = tree.get_item_area_rect(item, 0).get_center()
	event.ctrl_pressed = true
	event.pressed = true
	tree._gui_input(event)
	event.pressed = false
	tree._gui_input(event)
	await settle()
	check(dock._layers_rename_context.is_empty(), "Ctrl-click does not start rename")
	event.ctrl_pressed = false
	event.pressed = true
	tree._gui_input(event)
	var motion := InputEventMouseMotion.new()
	motion.position = event.position + Vector2(12, 0)
	tree._gui_input(motion)
	event.pressed = false
	tree._gui_input(event)
	await settle()
	check(dock._layers_rename_context.is_empty(), "drag movement cancels second-click rename")
	dock._select_tool(Canvas.ToolMode.TEXT)
	dock._canvas.create_text_draft(Rect2i(0, 0, 32, 32), "Name")
	dock._canvas.commit_text_draft()
	await settle()
	target = dock._layer_session.get_active_target()
	var text_id: String = target.selected_layer_id
	dock._panel_host.activate_panel("layers")
	dock._layers_multi_contexts.clear()
	dock._on_layers_tree_row_reclicked({"kind": "paint", "target_id": target.target_id, "node_id": text_id})
	await settle()
	check(dock._layers_rename_context.get("node_id") == text_id, "Text layer second click also starts rename")
	dock._cancel_layer_inline_rename()
	dock.free()

func selection_checks(dock: Control):
	dock._prepare_layer_operation()
	dock._layer_session.initialize_2d(Vector2i(32,32))
	var target = dock._layer_session.get_active_target()
	var base_id: String = target.selected_layer_id
	var ids: Array = []
	for i in range(5): ids.append(target.add_paint_layer("Layer %d" % i))
	ids.reverse()
	target.select_layer(base_id)
	dock._sync_canvas_to_active_layer()
	dock._refresh_layers_tree()
	dock._panel_host.activate_panel("layers")
	await settle()
	await click_tree(dock, ids[0])
	await click_tree(dock, ids[3], true)
	check(dock._selected_layer_ids(target.target_id).size() == 4, "Shift-click selects visible range")
	await click_tree(dock, ids[1], false, true)
	check(dock._selected_layer_ids(target.target_id).size() == 3 and not dock._selected_layer_ids(target.target_id).has(ids[1]), "Ctrl-click removes individual layer")
	await click_tree(dock, ids[4], false, true)
	check(dock._selected_layer_ids(target.target_id).size() == 4, "Ctrl-click adds individual layer")
	await click_tree(dock, ids[2], false, false, true)
	check(dock._selected_layer_ids(target.target_id).size() == 4, "right click preserves multi-selection")
	check(dock._layers_context_menu.get_item_index(dock.LAYER_CONTEXT_NEW_GROUP) >= 0, "multi-selection menu offers Group Selected")
	dock._layers_context_menu.hide()
	dock._on_layers_group_pressed()
	var groups: Array = target.nodes.filter(func(node): return node.is_group())
	check(groups.size() == 1, "group command creates one group")
	if groups.size() == 1:
		var ordered: Array = groups[0].children.map(func(node): return node.id)
		check(ordered == [ids[0], ids[2], ids[3], ids[4]], "group preserves selected stacking order")
	dock._undo()
	target = dock._layer_session.get_active_target()
	check(target.nodes.filter(func(node): return node.is_group()).is_empty(), "one undo restores ungrouped hierarchy")
	target.set_node_locked(ids[2], true)
	check(target.group_nodes([ids[0], ids[2]]).is_empty(), "grouping respects locks without partial mutation")

func bulk_checks(dock: Control):
	dock._prepare_layer_operation()
	dock._layer_session.initialize_2d(Vector2i(32,32))
	var target = dock._layer_session.get_active_target()
	var base: String = target.selected_layer_id
	var a: String = target.add_paint_layer("A")
	var b: String = target.add_paint_layer("B")
	var c: String = target.add_paint_layer("C")
	dock._sync_canvas_to_active_layer()
	dock._set_layer_multi_selection(target, [b, a])
	dock._refresh_layers_tree()
	var context := {"kind": "paint", "target_id": target.target_id, "node_id": b, "node_ids": [b, a]}
	dock._show_layers_context_menu(context, Vector2i(50,50))
	for command in [dock.LAYER_CONTEXT_SHOW_SELECTED, dock.LAYER_CONTEXT_HIDE_SELECTED, dock.LAYER_CONTEXT_LOCK_SELECTED, dock.LAYER_CONTEXT_UNLOCK_SELECTED, dock.LAYER_CONTEXT_DUPLICATE, dock.LAYER_CONTEXT_DELETE]:
		check(dock._layers_context_menu.get_item_index(command) >= 0, "bulk menu includes command %d" % command)
	dock._layers_context_menu.hide()
	var count: int = dock._history._undo_stack.size()
	dock._on_layers_context_menu_id_pressed(dock.LAYER_CONTEXT_HIDE_SELECTED)
	check(not target.find_node(a).visible and not target.find_node(b).visible and target.find_node(c).visible, "Hide affects exactly selected roots")
	check(dock._history._undo_stack.size() == count + 1, "bulk visibility is one undo action")
	dock._apply_layer_selection_action(context, "hide")
	check(dock._history._undo_stack.size() == count + 1, "ineffective bulk action creates no undo entry")
	dock._undo()
	target = dock._layer_session.get_active_target()
	check(target.find_node(a).visible and target.find_node(b).visible, "undo restores all visibility changes")
	dock._apply_layer_selection_action(context, "lock")
	check(target.find_node(a).locked and target.find_node(b).locked, "bulk lock protects selection")
	check(not target.can_apply_selection([a,b], "delete") and not target.can_apply_selection([a,c], "duplicate"), "locked mixed selections reject destructive actions")
	dock._apply_layer_selection_action(context, "unlock")
	dock._apply_layer_selection_action(context, "duplicate")
	check(target.get_paint_layer_count() == 6 and dock._selected_layer_ids(target.target_id).size() == 2, "duplicates select both new layers")
	dock._undo()
	target = dock._layer_session.get_active_target()
	check(target.get_paint_layer_count() == 4, "one undo removes all duplicates")
	dock._request_layer_delete(context)
	check(dock._layers_delete_dialog.visible, "bulk delete uses existing confirmation")
	check(dock._layers_delete_dialog.title == "Delete 2 layers" and dock._layers_delete_dialog.dialog_text == "Delete 2 layers?" and dock._layers_delete_dialog.ok_button_text == "Delete 2 items", "bulk delete title, message, and button show actual count")
	dock._layers_delete_dialog.hide()
	dock._confirm_layer_delete()
	check(target.get_paint_layer_count() == 2 and not target.find_node(a) and not target.find_node(b), "confirmed deletion removes selection together")
	dock._undo()
	target = dock._layer_session.get_active_target()
	check(not target.can_apply_selection([base,a,b,c], "delete"), "combined deletion protects final paint layer")
	var outer: String = target.add_group("Outer")
	var inner: String = target.add_group("Inner", outer)
	check(target.move_nodes([a,b], inner, 0), "multiple layers move into nested subgroup")
	check(target.find_node(inner).children.map(func(node): return node.id) == [b,a], "move preserves model stacking order")
	dock._configure_layer_delete_count(target, [outer,inner,a])
	check(dock._layers_delete_dialog.title == "Delete 2 layers and 2 groups" and dock._layers_delete_dialog.ok_button_text == "Delete 4 items", "delete counts nested contents without counting selected descendants twice")
	dock._configure_layer_delete_count(target, [c])
	check(dock._layers_delete_dialog.title == "Delete 1 layer" and dock._layers_delete_dialog.ok_button_text == "Delete 1 item", "single deletion resets plural dialog labels")
	check(target.selection_roots([outer, inner, a]) == [outer], "selected ancestor includes descendants once")
	check(target.selection_move_plan([outer,c], inner, 0).is_empty(), "multi-move prevents ancestor cycles")
	target.set_node_locked(a, true)
	check(not target.move_nodes([a,c], outer, 0) and str(target.get_node_location(c).parent_group_id).is_empty(), "locked member rejects whole move")
	target.set_node_locked(a, false)
	check(target.move_nodes([a,b], "", target.nodes.size()), "multiple layers move back out of nested group")
	check(target.nodes.slice(-2).map(func(node): return node.id) == [b,a], "root move preserves relative order")
	check(not target.move_nodes([a,b], "", target.nodes.size()), "dropping into same position is a no-op")
	dock._sync_canvas_to_active_layer()
	dock._set_layer_multi_selection(target, [b,a])
	dock._refresh_layers_tree()
	dock._panel_host.activate_panel("layers")
	await settle()
	await drag_selection(dock, b, inner)
	target = dock._layer_session.get_active_target()
	check(target.find_node(inner).children.map(func(node): return node.id) == [b,a], "native tree drag moves entire selection into subgroup")
	check(dock._selected_layer_ids(target.target_id).size() == 2, "moved layers remain multi-selected")
	dock._undo()
	target = dock._layer_session.get_active_target()
	check(str(target.get_node_location(a).parent_group_id).is_empty() and str(target.get_node_location(b).parent_group_id).is_empty(), "one undo restores multi-drag hierarchy")

func drag_selection(dock, source_id: String, group_id: String):
	var tree: Tree = dock._layers_tree
	var target = dock._layer_session.get_active_target()
	var source: TreeItem = dock._find_layers_tree_item(tree.get_root(), "paint", target.target_id, source_id, "")
	var destination: TreeItem = dock._find_layers_tree_item(tree.get_root(), "group", target.target_id, group_id, "")
	var start: Vector2 = tree.global_position + tree.get_item_area_rect(source, 0).get_center()
	var finish: Vector2 = tree.global_position + tree.get_item_area_rect(destination, 0).get_center()
	var press := InputEventMouseButton.new()
	press.button_index = MOUSE_BUTTON_LEFT
	press.pressed = true
	press.position = start
	press.global_position = start
	root.push_input(press)
	var motion := InputEventMouseMotion.new()
	motion.button_mask = MOUSE_BUTTON_MASK_LEFT
	motion.position = start + Vector2(15,0)
	motion.global_position = motion.position
	motion.relative = Vector2(15,0)
	root.push_input(motion)
	await process_frame
	var payload: Variant = root.gui_get_drag_data()
	check(payload is Dictionary and payload.gddraw_layer_node.node_ids.size() == 2, "dragging selected row carries all selected IDs")
	motion.position = finish
	motion.global_position = finish
	motion.relative = finish - start
	root.push_input(motion)
	press.pressed = false
	press.position = finish
	press.global_position = finish
	root.push_input(press)
	await settle()
	if "--forwarded-drag" in OS.get_cmdline_user_args():
		# The sandbox DisplayServer can return invalid system pointer positions
		# during native dragging. Feed the known tree-local drop point directly.
		var local_finish := finish - tree.global_position
		check(tree._can_drop_data(local_finish, payload), "forwarded multi-drag accepts subgroup destination")
		tree._drop_data(local_finish, payload)
		await settle()

func panel_preference_checks(dock):
	dock._select_tool(Canvas.ToolMode.BRUSH)
	dock._on_gradient_always_show_panel_toggled(true)
	check(dock._panel_host.panels.has("gradient") and not dock._panel_host.is_panel_open("gradient"), "always-visible preference exposes button without forcing panel open")
	dock._panel_host.activate_panel("gradient")
	check(not dock._gradient_panel.empty_hint.visible, "persistent panel previews next gradient on ordinary layers")
	dock._select_tool(Canvas.ToolMode.GRADIENT)
	check(not dock._gradient_panel.empty_hint.visible, "Gradient tool restores stop controls")
	dock._select_tool(Canvas.ToolMode.BRUSH)
	check(dock._panel_host.panels.has("gradient") and dock._panel_host.is_panel_open("gradient"), "persistent Gradient panel survives tool switch")
	dock._panel_host.close_panel("gradient")
	dock._select_tool(Canvas.ToolMode.GRADIENT)
	check(dock._panel_host.is_panel_active("gradient"), "selecting Gradient opens and activates its helper")
	var gradient_button: Button = dock._panel_host.panels.gradient.button
	check(gradient_button.button_pressed and str(gradient_button.get_meta("applied_icon_path", "")).ends_with("gradient_1.svg"), "visible Gradient panel has highlighted rail icon")
	dock._panel_host.activate_panel("layers")
	check(gradient_button.button_pressed, "inactive open Gradient tab keeps rail highlighted")
	gradient_button.set_pressed_no_signal(false)
	dock._panel_host.activate_panel("gradient")
	check(gradient_button.button_pressed and str(gradient_button.get_meta("applied_icon_path", "")).ends_with("gradient_1.svg"), "activating existing tab resynchronizes its rail selection")
	dock._panel_host.close_panel("gradient")
	check(not gradient_button.button_pressed and str(gradient_button.get_meta("applied_icon_path", "")).ends_with("gradient_0.svg"), "closing Gradient clears rail highlight")
	dock._select_tool(Canvas.ToolMode.BRUSH)
	dock._on_gradient_always_show_panel_toggled(false)
	check(not dock._panel_host.panels.has("gradient"), "disabling preference restores contextual availability")
	dock._select_tool(Canvas.ToolMode.GRADIENT)
	var group_id: String = dock._panel_host.group_for_panel("gradient").id
	dock._on_gradient_always_show_panel_toggled(true)
	check(dock._panel_host.is_panel_open("gradient") and dock._panel_host.group_for_panel("gradient").id == group_id, "enabling preference preserves an already-open contextual panel")
	dock._select_tool(Canvas.ToolMode.BRUSH)
	dock._on_gradient_always_show_panel_toggled(false)

func gradient_context_checks(dock):
	dock._prepare_layer_operation()
	dock._layer_session.initialize_2d(Vector2i(32,32))
	dock._sync_canvas_to_active_layer()
	var target = dock._layer_session.get_active_target()
	var paint_id: String = target.selected_layer_id
	var canvas = dock._canvas
	dock._on_gradient_always_show_panel_toggled(true)
	dock._on_gradient_default_output_selected(0)
	dock._select_tool(Canvas.ToolMode.GRADIENT)
	canvas.gradient_stops = [{"position": 0.0, "color": Color.BLUE}, {"position": 0.5, "color": Color.GREEN}, {"position": 1.0, "color": Color.YELLOW}]
	canvas.gradient_opacity = 0.4
	canvas.begin_gradient(Vector2(2,2))
	canvas.update_gradient(Vector2(28,2))
	canvas.commit_gradient()
	var gradient_id: String = target.selected_layer_id
	var saved: Dictionary = target.find_node(gradient_id).gradient_recipe.duplicate(true)
	dock._set_foreground_color(Color.RED)
	dock._set_background_color(Color.CYAN)
	check(canvas.get_gradient_stops().size() == 3 and canvas.get_gradient_stops()[0].color == Color.BLUE, "drawing color changes preserve selected gradient recipe controls")
	choose(dock, paint_id, Canvas.ToolMode.BRUSH)
	check(canvas.get_gradient_stops().size() == 2 and canvas.get_gradient_stops()[0].color == Color.RED and canvas.get_gradient_stops()[1].color == Color.CYAN, "ordinary layer resets saved stops to drawing colors")
	check(canvas.gradient_opacity == 1.0 and not canvas.gradient_transparent, "ordinary layer clears inherited opacity and transparency mode")
	dock._set_background_color(Color.MAGENTA)
	check(dock._gradient_panel.rows[1].picker.color == Color.MAGENTA, "idle panel immediately follows drawing color changes")
	dock._select_tool(Canvas.ToolMode.GRADIENT)
	dock._panel_host.close_panel("gradient")
	canvas.grab_focus()
	canvas.begin_gradient(Vector2(3,3))
	check(dock._panel_host.is_panel_active("gradient") and canvas.has_focus(), "first stroke opens closed helper without taking canvas focus")
	check(canvas._gradient_settings.stops == canvas.get_gradient_stops(), "stroke uses the exact stops shown in helper")
	canvas.edit_gradient_stop(0, Color.GREEN, 0)
	dock._set_foreground_color(Color.WHITE)
	check(canvas.get_gradient_stops()[0].color == Color.GREEN, "drawing color changes preserve active draft edits")
	canvas.cancel_gradient()
	choose(dock, gradient_id, Canvas.ToolMode.GRADIENT)
	check(target.find_node(gradient_id).gradient_recipe == saved and canvas.get_gradient_stops().size() == 3, "returning to saved gradient restores its own stops")
	await settle()
